#ifdef _DEBUG 
#if 0
#pragma comment( lib, "IlmImfd.lib")  
#pragma comment( lib, "libjasperd.lib")  
#pragma comment( lib, "libjpegd.lib")  
#pragma comment( lib, "libpngd.lib")  
#pragma comment( lib, "libtiffd.lib")  
#pragma comment( lib, "zlibd.lib") 
#endif
#pragma comment( lib, "opencv_calib3d2413d.lib" )
#pragma comment( lib, "opencv_contrib2413d.lib" )
#pragma comment( lib, "opencv_core2413d.lib" )
#pragma comment( lib, "opencv_features2d2413d.lib" )
#pragma comment( lib, "opencv_flann2413d.lib" )
#pragma comment( lib, "opencv_gpu2413d.lib" )
#pragma comment( lib, "opencv_highgui2413d.lib" )
#pragma comment( lib, "opencv_imgproc2413d.lib" )
#pragma comment( lib, "opencv_legacy2413d.lib" )
#pragma comment( lib, "opencv_ml2413d.lib" )
#pragma comment( lib, "opencv_nonfree2413d.lib" )
#pragma comment( lib, "opencv_objdetect2413d.lib" )
#pragma comment( lib, "opencv_ocl2413d.lib" )
#pragma comment( lib, "opencv_photo2413d.lib" )
#pragma comment( lib, "opencv_stitching2413d.lib" )
#pragma comment( lib, "opencv_superres2413d.lib" )
#pragma comment( lib, "opencv_ts2413d.lib" )
#pragma comment( lib, "opencv_video2413d.lib" )
#pragma comment( lib, "opencv_videostab2413d.lib" )
#else 
#pragma comment( lib, "IlmImf.lib")  
#pragma comment( lib, "libjasper.lib")  
#pragma comment( lib, "libjpeg.lib")  
#pragma comment( lib, "libpng.lib")  
#pragma comment( lib, "libtiff.lib")  
#pragma comment( lib, "zlib.lib") 
#pragma comment( lib, "opencv_calib3d2413.lib" )
#pragma comment( lib, "opencv_contrib2413.lib" )
#pragma comment( lib, "opencv_core2413.lib" )
#pragma comment( lib, "opencv_features2d2413.lib" )
#pragma comment( lib, "opencv_flann2413.lib" )
#pragma comment( lib, "opencv_gpu2413.lib" )
#pragma comment( lib, "opencv_highgui2413.lib" )
#pragma comment( lib, "opencv_imgproc2413.lib" )
#pragma comment( lib, "opencv_legacy2413.lib" )
#pragma comment( lib, "opencv_ml2413.lib" )
#pragma comment( lib, "opencv_nonfree2413.lib" )
#pragma comment( lib, "opencv_objdetect2413.lib" )
#pragma comment( lib, "opencv_ocl2413.lib" )
#pragma comment( lib, "opencv_photo2413.lib" )
#pragma comment( lib, "opencv_stitching2413.lib" )
#pragma comment( lib, "opencv_superres2413.lib" )
#pragma comment( lib, "opencv_ts2413.lib" )
#pragma comment( lib, "opencv_video2413.lib" )
#pragma comment( lib, "opencv_videostab2413.lib" )
#endif

#pragma comment( lib, "User32.lib")
#pragma comment( lib, "gdi32.lib")
#pragma comment( lib, "vfw32.lib" )  
#pragma comment( lib, "comctl32.lib" )  
#pragma comment( lib, "AdvAPI32.lib" )
#pragma comment( lib, "ole32.lib" )
#pragma comment( lib, "advapi32.lib")
#pragma comment( lib, "oleaut32.lib")